### ISSUE TITLE
Incompatable with older mc versions

### ISSUE THREAD

**Issue by SunnySlopes** [EngineHub/WorldEditCUI#39]
when i use mc1.14.4/1.15.2, WE cui would prevent me from entering any of my world at 100%

**Comment by zml2008** [comment]
Unfortunately we don't have the resources to actively maintain WorldEditCUI for older versions of the game. If you provided a full crash report and `latest.log` from when you're trying to use those versions of the mod we might be able to give some advice, but otherwise there's not a ton we can offer.

If you or a developer you can find are able to provide a PR fixing whatever issue we have, we'd be happy to review it as time permits, but our focus will continue to be 1.16.5+.

**Comment by CatEricka** [comment]
I did some tests:

all minecraft version: 1.15.2
java: 1.8

---
test1:

- fabric loader: 0.11.1
- fabric api: **0.28.5+1.15**
- WorldEditCUI: 1.15.2_03
- Freeze when opening single player save, log: [latest.log](https://github.com/mikroskeem/WorldEditCUI/files/6019816/latest.log)

---
test2:

- fabric loader: 0.11.1
- fabric api: **0.23.1+1.15**
- WorldEditCUI: 1.15.2_03
- working fine

---

**Comment by zml2008** [comment]
Ah, seems to be something with Fabric's new networking API... Should be a relatively straightforward fix -- but sadly because of how curseforge works releasing an update for 1.15 without an update for 1.16 makes it send users to the wrong version. Hopefully will get a chance to push out an update in March, and can look at doing a 1.15.2 update then.

**Comment by CatEricka** [comment]
minecraft: 1.14.4
java: 1.8
fabric loader: 0.11.1
fabric api: 0.28.5+1.14
WorldEditCUI: 1.14.4_03

```log
[14:31:25] [Server thread/INFO]: Aya[local:E:7bd8825b] logged in with entity id 181 at (-167.5, 68.0, -4.5)
[14:31:25] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Cannot send packet to server while not in game!
	at net.fabricmc.fabric.impl.networking.ClientSidePacketRegistryImpl.sendToServer(ClientSidePacketRegistryImpl.java:51) ~[b8b37cf1-ff59-4937-8605-8aad65833d1c.jar:?]
	at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:70) ~[b8b37cf1-ff59-4937-8605-8aad65833d1c.jar:?]
	at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:89) ~[b8b37cf1-ff59-4937-8605-8aad65833d1c.jar:?]
	at eu.mikroskeem.worldeditcui.FabricModWorldEditCUI.helo(FabricModWorldEditCUI.java:169) ~[WorldEditCUI-1.14.4_03.jar:?]
	at eu.mikroskeem.worldeditcui.FabricModWorldEditCUI.onJoinGame(FabricModWorldEditCUI.java:148) ~[WorldEditCUI-1.14.4_03.jar:?]
	at net.minecraft.class_634.handler$zzk000$onGameJoin(class_634.java:3269) ~[intermediary-1.14.4.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:345) ~[intermediary-1.14.4.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:76) ~[intermediary-1.14.4.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:13) ~[intermediary-1.14.4.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.14.4.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.14.4.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.14.4.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.14.4.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.14.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:915) [intermediary-1.14.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:410) [intermediary-1.14.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-1.14.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
```

Seems to be the same problem
