### ISSUE TITLE
Crashes when loading a single player world with multiconnect installed

### ISSUE THREAD

**Issue by VL4DST3R** [EngineHub/WorldEditCUI#67]
### WorldEditCUI Version

1.19+01

### Fabric Version

0.14.8

### Fabric API Version

0.57.0+1.19

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

Not sure if this is on multiconnect or WorldeditCUI to fix, but im making the ticket here regardless: When having both multiconnect and WorldeditCUI installed if it try to open a SP world i get kicked out with the following stack trace:

```
java.util.concurrent.RejectedExecutionException: event executor terminated
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:932)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:825)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:815)
	at net.earthcomputer.multiconnect.impl.PacketSystem.sendToServer(PacketSystem.java:155)
	at net.earthcomputer.multiconnect.protocols.generic.CustomPayloadHandler.forceSendIdentifierCustomPayload(CustomPayloadHandler.java:65)
	at net.earthcomputer.multiconnect.impl.APIImpl.forceSendCustomPayload(APIImpl.java:57)
	at org.enginehub.worldeditcui.fabric.CUINetworking.sendUnchecked(CUINetworking.java:42)
	at org.enginehub.worldeditcui.fabric.CUINetworking.send(CUINetworking.java:33)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.helo(FabricModWorldEditCUI.java:196)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.onTick(FabricModWorldEditCUI.java:144)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$bkd000$onEndTick(MinecraftClient:13890)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1869)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Expected Behavior

To work like it does in multiplayer.

### Reproduction Steps

1. Load/Make a single player map
2. Crash

**Comment by TheOneAndOnlyDanSan** [comment]
when it doesn't crash it says disconnected and sends me to the server select screen

**Comment by zml2008** [comment]
could you provide the full crash report file for this? or at the very least, the version of multiconnect you're testing with
