### ISSUE TITLE
minecraft crashes when cleaing selection

### ISSUE THREAD

**Issue by TheOneAndOnlyDanSan** [EngineHub/WorldEditCUI#70]
### WorldEditCUI Version

1.19+01

### Fabric Version

0.14.9-1.19.2

### Fabric API Version

0.58.6+1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_44099(java.lang.String)'
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.onTick(FabricModWorldEditCUI.java:124)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zdo000$onEndTick(class_310.java:3973)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Expected Behavior

not crash

### Reproduction Steps

1. open world 
2. press "Clear WorldEdit selection" button

### Anything Else?

i'm not using any other mods only fabric api and worldedit

**Comment by Fyrinlight** [comment]
Recompile with the latest version of minecraft. If you use the officially published worldeditCUI jar, it is compiled with the wrong version and therefor crashes.
